dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm run build:dev
  - npm run lint
  - npm run lint:extra || true
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - npm install "republicprotocol/renex-sdk-ts#$BRANCH"
