import RenExSDK from "../index";
import { AtomicBalanceDetails, AtomicConnectionStatus } from "../types";
export declare const currentAtomConnectionStatus: (sdk: RenExSDK) => AtomicConnectionStatus;
export declare const atomConnected: (sdk: RenExSDK) => boolean;
export declare const resetAtomConnection: (sdk: RenExSDK) => Promise<AtomicConnectionStatus>;
export declare const refreshAtomConnectionStatus: (sdk: RenExSDK) => Promise<AtomicConnectionStatus>;
export declare const authorizeAtom: (sdk: RenExSDK) => Promise<AtomicConnectionStatus>;
export declare const supportedAtomicTokens: (sdk: RenExSDK) => Promise<string[]>;
export declare const atomicAddresses: (tokens: string[]) => Promise<string[]>;
export declare const atomicBalances: (sdk: RenExSDK, tokens: string[]) => Promise<Map<string, AtomicBalanceDetails>>;
