import { BN } from "bn.js";
import RenExSDK from "../index";
import { AtomicConnectionStatus } from "../types";
export declare const currentAtomConnectionStatus: (sdk: RenExSDK) => AtomicConnectionStatus;
export declare const atomConnected: (sdk: RenExSDK) => boolean;
export declare const resetAtomConnection: (sdk: RenExSDK) => Promise<AtomicConnectionStatus>;
export declare const refreshAtomConnectionStatus: (sdk: RenExSDK) => Promise<AtomicConnectionStatus>;
export declare const authorizeAtom: (sdk: RenExSDK) => Promise<AtomicConnectionStatus>;
export declare const supportedTokens: (sdk: RenExSDK) => Promise<number[]>;
export declare const atomicBalances: (sdk: RenExSDK, tokens: number[]) => Promise<BN[]>;
export declare const atomicBalance: (sdk: RenExSDK, token: number) => Promise<BN>;
export declare const atomicAddresses: (sdk: RenExSDK, tokens: number[]) => Promise<string[]>;
export declare const atomicAddress: (sdk: RenExSDK, token: number) => Promise<string>;
export declare const usableAtomicBalances: (sdk: RenExSDK, tokens: number[]) => Promise<BN[]>;
export declare const usableAtomicBalance: (sdk: RenExSDK, token: number) => Promise<BN>;
